### ISSUE TITLE
Support for php 5.4

### ISSUE THREAD

**Issue by leroy0211** [mapado/rest-client-sdk#12]
At the moment your only lib which requires a minimum of php 5.5 is the guzzle client.
Could you run the tests with guzzle `~5.3.0` also, to check if the SDK still works on [PHP 5.4](https://packagist.org/packages/guzzlehttp/guzzle#5.3.0)?

**Comment by jdeniau** [comment]
As PHP 5.4 is [not maintained anymore](http://php.net/supported-versions.php), and as I remember Guzzle 6 breaks things in its implementation compared to Guzzle 5, I will not treat this as a priority.

As Guzzle is for the moment needed, the component won't work on PHP 5.4 I think.

A good think to try though is to use another PSR-7 compliant component, maybe compatible 5.4, to see if everything works fine.

**Comment by leroy0211** [comment]
Ok. 
Well you are right. Better drop the php 5.4 support and continue on with 5.5 as a minimum
