### ISSUE TITLE
@Attribute name annotation giving NULL when the class parameter name is different

### ISSUE THREAD

**Issue by leroy0211** [mapado/rest-client-sdk#13]
First of all let me define my resouces. 

I use this Hydra API: http://www.markus-lanthaler.com/hydra/event-api/events/41 
I created a class `Event` like:

```
/**
 * Class Event
 *
 * @package Acme\DemoBundle\Entity
 * @Rest\Entity(key="events", client="Acme\DemoBundle\Command\BasicClient")
 */
class Event
{
    /**
     * @var int
     * @Rest\Id()
     */
    protected $id;

    /**
     * @var string
     * @Rest\Attribute(name="name", type="string")
     */
    protected $firstName;

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return string
     */
    public function getFirstName()
    {
        return $this->firstName;
    }

    /**
     * @param string $firstName
     */
    public function setFirstName($firstName)
    {
        $this->firstName = $firstName;
    }

}
```

Now when I try to get the Event Entity the Id is correct. But the `$firstName` attribute gives me back `NULL`.

When I change the `$firstName` attribute to `$name`, everything works like a charm. 

It looks like the @Attribute name annotation doesn't seem to work as it should.

**Comment by jdeniau** [comment]
@rubiodamian Can you copy the class you are using ? thanks

**Comment by jdeniau** [comment]
Ok it's probably due to the fact that it's an array (the code is pretty ugly for arrays, because it can be a relation or an array), I will try to look at it tomorrow

**Comment by jdeniau** [comment]
Do you think it's related to #75 or not ?

**Comment by rubiodamian** [comment]
Maybe it is related because it's in the same part of code i think

**Comment by jdeniau** [comment]
Can you see if the bug is still present in the 0.29.0 ?

**Comment by rubiodamian** [comment]
bug fixed!! :+1:

**Comment by jdeniau** [comment]
Great, I'm closing this
