### ISSUE TITLE
paginated hydra collections support

### ISSUE THREAD

**Issue by jmfeurprier** [mapado/rest-client-sdk#54]
Not sure if this is an issue on the SDK side or the API side.

I'm querying an API endpoint which should return a collection of items (CGET), with a page (1) and a number of items per page (10), and I would expect to access the real total item count (5000), to build a pagination system. This information seem to be available through the HydraPaginatedCollection class and getTotalItems() method, but I always get a HydraCollection object, which only shows the number of returned items (10).

I'm making an API call with these parameters:

`GET domain.tld/items?foo=bar&order[name]=ASC&itemsPerPage=10&page=1`

And here is a sample of the response :

```
{
    "@context": "\/contexts\/Item",
    "@id": "\/items",
    "@type": "hydra:Collection",
    "hydra:member": [
        {
            "@id": "\/items\/bd87b2df-000b-11e7-a37a-0242ac150003",
            "@type": "Item",
            "id": "bd87b2df-000b-11e7-a37a-0242ac150003",
            "name": "foo"
        },
( more items here )
    ],
    "hydra:totalItems": 5000,
    "hydra:view": {
        "@id": "\/items?foo=bar&order%5Bname%5D=ASC&itemsPerPage=10&page=1",
        "@type": "hydra:PartialCollectionView",
        "hydra:first": "\/items?foo=bar&order%5Bname%5D=ASC&itemsPerPage=10&page=1",
        "hydra:last": "\/items?foo=bar&order%5Bname%5D=ASC&itemsPerPage=10&page=500",
        "hydra:next": "\/items?foo=bar&order%5Bname%5D=ASC&itemsPerPage=10&page=2"
    },
    "hydra:search": {
        ( ... irrelevant stuff here ... )
    }
}
```

The ModelHydrator::deserializeAll() method seems to rely on the value of the `@type` node to build a HydraPaginatedCollection instead of a HydraCollection :

```
        $hydratedList = new HydraCollection($data);

        if (!empty($data['@type'])) {
            if ($data['@type'] === 'hydra:PagedCollection') {
                $hydratedList = new HydraPaginatedCollection($data);
            }
        }

        return $hydratedList;
```

But in my response, the value of `@type` is 'hydra:Collection'.

Do you think the condition is too strict, or the API response too "loose" ? (API is driven by [api-platform](https://api-platform.com/)).

**Comment by jmfeurprier** [comment]
I read through the source code, past and present of api-platform and they seem to have totally dropped the "hydra:PagedCollection" type (only found 2 occurences in a documentation helper class) :/

**Comment by jdeniau** [comment]
So cool you opened this issue, because it is "kind of" fixed in a PR I forgot to merge :)

Maybe you can review it as my collegues does not really watch their github notifications:

https://github.com/mapado/rest-client-sdk/pull/53

You still will not have a HydraCollection object, but the class would not work with the `hydra:view` anyhow, but you will have a [Collection](https://github.com/mapado/rest-client-sdk/blob/feat-workingWithHal/src/Collection/Collection.php) object having a `getExtraProperty($key)` method. The `HydraPaginatedCollection` is now just a helper class extending the Collection one.

**Comment by jmfeurprier** [comment]
I took a look at the PR, it seems to be OK for what we need. Any idea when it could be released ?

Thanks !

**Comment by jdeniau** [comment]
Will do tomorrow

**Comment by jdeniau** [comment]
Fixed in 0.20.0, See the CHANGELOG.md for BC

**Comment by jdeniau** [comment]
Added in the Bundle configuration in the `0.19.0` version of the bundle. See [Readme](https://github.com/mapado/rest-client-sdk-bundle/blob/master/README.md) for more informations

**Comment by jmfeurprier** [comment]
Updated the package today, everything works as expected (I just had to rename HydraCollection to Collection as described in the breaking changes list and to use the new getExtraProperty(...) method to make pagination work).

Thanks !

**Comment by jdeniau** [comment]
Great, thanks for your comment !
