### ISSUE TITLE
More recent version of ocramius/proxy-manager

### ISSUE THREAD

**Issue by hvalcourtSerdy** [mapado/rest-client-sdk#57]
Hi,

is it possible to eventually update ocramius/proxy-manager in Composer ?

I ask because the actual version do not support PHP7 Scalar type declarations
http://php.net/manual/fr/migration70.new-features.php

Thanks again

**Comment by jdeniau** [comment]
Yes I will try to do this.

Little sad that PHP 5 support was dropped though, but I prefer evolving the library to PHP 7 instead of maintaining PHP 5.

As the BC breaks are important, it will take some time to check everything, but I will try to do it during the next week max.

**Comment by hvalcourtSerdy** [comment]
Hi,

yes big BC, I can help to test when you will be ready if you need to

**Comment by jdeniau** [comment]
started to work on it in https://github.com/mapado/rest-client-sdk/tree/jd-feat-proxyManagerV2 but tests are failing for now. 
Will dig deeper next week ;)

**Comment by jmfeurprier** [comment]
Hi there, is this issue still in development?

Thanks!

**Comment by jdeniau** [comment]
Hi, 

sorry but I did not advance on this now. If you want to investigate on the jd-feat-proxyManagerV2 branch, it will be really helpful ! :)
