### ISSUE TITLE
Creating relation entities even when they aren't resources

### ISSUE THREAD

**Issue by rubiodamian** [mapado/rest-client-sdk#75]
When the serializer deserialize the entity with:
`
      $agente = $this->get('mapado.rest_client_sdk.agentes')->getRepository('agentes')->find(20);
`
if that entity, in this case "Agentes", have a relation with other entity but that entity doesn't have an iri identifier the app throws an exception like this: 
![image](https://user-images.githubusercontent.com/1789406/38693851-873dda98-3e5e-11e8-8cd0-ecd7553408c6.png)
 That error means that the entity is handled like an resourse but it isn't.
But maybe something like other annotation or maybe an if condition on the desiarialization can make that a non resourse entity relation be handled as a rest relation.

i made something like that with the controller scope:

```php
$serializer = $this->get('mapado.rest_client_sdk.agentes')->getSerializer();

$agente = $this->get('mapado.rest_client_sdk.agentes')->getRepository('agentes')->find(20);

$agente->setTipoCuil($serializer->deserialize($agente->getTipoCuil(), 'App\Entity\TipoCuil'));
```
This only works if you put the rest\entity annotation on the relation entity:

```php
/**
 * TipoCuil
 * @Rest\Entity(key="tipoCuil")
 */
class TipoCuil`
```
and in Agentes: 
```php
`/**
 * @var array
 *
 * @Rest\Attribute(name="tipoCuil", type="array")
 */
 private $tipoCuil;
```

this would make all relationships be objects and no array like now when the relation is an nono iri relation.

sorry for my bad english and for the latest issues. This is a really good and useful project and i want to help with everything ahah

**Comment by jdeniau** [comment]
No problem for the bad english, and thank you for the issues, it help improving the project :+1: 

About your issue, if I understood correctly: 

You have two entities `Agentes` and `TipoCuil`, but your `TipoCuil` entity does not have any endpoint nor iri exposed ?

You only have the endpoint: `/agentes` and `/agentes/{id}` but no `/tipocuil` nor `/tipocuil/{id}` am I right ?

~If so, I think your `TipoCuil` entity should not have the annotation `@Rest\Entity`~

If I still understand correctly, you use the `Rest\Entity` annotation mainly for deserialization purpose, but your `Agentes::tipoCuil` relation could only be a simple array, it would work fine, am I right ? 

If so, the `Rest\Entity` is like a helper for deserialization. I will think about it today, if it's more a serializer think and if I have a solution for you, or if I push something to treat this case.

**Comment by jdeniau** [comment]
Well as I read your stacktrace, it looks like there is a call to https://github.com/mapado/rest-client-sdk/blob/master/src/Model/Serializer.php#L132, with the string `CDI` as parameter. So it seems like it's not an object ?

Can you paste the return of your API call to help me diagnose your case ? (with Symfony and the `rest-client-sdk-bundle`, you can see it in the web debug toolbar)

**Comment by rubiodamian** [comment]
> You only have the endpoint: /agentes and /agentes/{id} but no /tipocuil nor /tipocuil/{id} am I right ?

exactly!

sometimes a relation entity on the api doesn't have an end point, becouse you just dont'n want to expose that entity. So it's still an relation entity but on the response it will be an array.
I know that,  in this case "TipoCuil" isn't a Rest\entity but is still a relation entity.

> Well as I read your stacktrace, it looks like there is a call to https://github.com/mapado/rest-client-sdk/blob/master/src/Model/Serializer.php#L132, with the string CDI as parameter. So it seems like it's not an object ?

yes, is an array. The serializer takes tipoCuil field and checks if the field is an Iri or not, so if TipoCuil is a Rest\enity the serialier will try to make a proxy for it. But, this field is only an entity not a rest\entity.
So that im trying to say is that, what if the relation entities can be a Rest\entity, an entity, an array or native types (int, string,etc)?
something like @rest\attribute(name="tipoCuil", type="object", class="App\Entity\TipoCuil")

**Comment by jdeniau** [comment]
Started to work on this in `https://github.com/mapado/rest-client-sdk/compare/jd-fix-issue75`.

It should work with ManyToOne relation, but not on OneToMany relation.

It's easier than it looked liked first, you just have to set `@Rest\Entity` on both your entities and configure a `@Rest\ManyToOne` relation on `Agentes::tipoCuil`

I will work on OneToMany relations tomorrow

**Comment by jdeniau** [comment]
0.29.0 released with the fix
